### ISSUE TITLE
backend anti-cheat for problem rush

### ISSUE THREAD

**Issue by PerpetualCreativity** [The-Mu-Foundation/Mutorials#273]

**Comment by PresidentPlant** [comment]
By anti-cheat, you mean blocking the requests with ridiculous scores that were sent to `train/rush/results`, right?

If so, we could add a variable 'questionCount' inside `userSchema.rush` to make sure the users have a "reasonable" score. Or, we could update their highscore whenever the answer's checked and just update the database each time. Either way requires a lot of database updates. This isn't much of an 'anti-cheat', but just using a key to encrypt/hide the data from plain sight and/.or minimizing the js code seemed to deter anybody who wanted to cheat, since it's slightly more harder. Maybe we could do this instead?

**Comment by TheFalloutOf76** [comment]
fixed

**Comment by dannyridel** [comment]
fixed
