### ISSUE TITLE
Name display bug

### ISSUE THREAD

**Issue by PerpetualCreativity** [The-Mu-Foundation/Mutorials#382]
In classes, *some* students' names aren't showing.

(I suspect, but have not confirmed, that usernames with non-alpha chars are breaking something in the dashboard.)

**Comment by nicktolhurst** [comment]
On the class dashboard (`/class/manage/[classCode]`), the **[username]'s stats** section is pulling from `profile.name` in the db which, in all my tests, was left unpopulated. @PerpetualCreativity, Is this where the bug was noticed?

I was about to put in a PR to swap it over to `ign`, then I realised the way _username_ is referenced across the site varies between the `ign` property and the `profile.name` property. 

For example, `profile/[username]` shows the username as **Unnamed User** as it's wanting `profile.name` from the db too.

Should the site use `profile.name` sitewide, and only `ign` to log in? `profile.name` could default to `ign` on signup until overridden in the settings.

Let me know your thoughts, I'm happy to create a PR for this.

**Comment by PerpetualCreativity** [comment]
@nicktolhurst

> On the class dashboard (/class/manage/[classCode]), the [username]'s stats section is pulling from profile.name in the db which, in all my tests, was left unpopulated. @PerpetualCreativity, Is this where the bug was noticed?

I'm pretty sure that's where the bug is.

> Should the site use profile.name sitewide, and only ign to log in?

We were thinking something like GitHub - if you look at a person's profile (on Mutorials, if its public) you'll see their name, otherwise you see their username everywhere else. The exception is for teachers (`class/dash`), who would probably prefer the full name vs the username.

> profile.name could default to ign on signup until overridden in the settings.

This sounds good - it should fix this issue and is intuitive. PR welcome.

Let me know whether this makes sense or whether we should go another route.
